import { User, RatingChange, Submission, Problem, Contest } from '../types';

export const generateFallbackUser = (handle: string): User => ({
    handle,
    contribution: 42,
    rank: 'expert',
    rating: 1650,
    maxRank: 'candidate master',
    maxRating: 1910,
    lastOnlineTimeSeconds: Math.floor(Date.now() / 1000) - 3600,
    registrationTimeSeconds: Math.floor(Date.now() / 1000) - 31536000 * 2,
    friendOfCount: 153,
    avatar: 'https://userpic.codeforces.org/no-avatar.jpg',
    titlePhoto: 'https://userpic.codeforces.org/no-avatar.jpg',
});

export const generateFallbackRatingHistory = (
    handle: string,
): RatingChange[] => [
    {
        contestId: 1800,
        contestName: 'Codeforces Round 850 (Div. 2)',
        handle,
        rank: 450,
        ratingUpdateTimeSeconds:
            Math.floor(Date.now() / 1000) - 100 * 24 * 3600,
        oldRating: 1400,
        newRating: 1480,
    },
    {
        contestId: 1810,
        contestName: 'Codeforces Round 860 (Div. 2)',
        handle,
        rank: 250,
        ratingUpdateTimeSeconds: Math.floor(Date.now() / 1000) - 80 * 24 * 3600,
        oldRating: 1480,
        newRating: 1550,
    },
    {
        contestId: 1820,
        contestName: 'Codeforces Round 870 (Div. 2)',
        handle,
        rank: 180,
        ratingUpdateTimeSeconds: Math.floor(Date.now() / 1000) - 60 * 24 * 3600,
        oldRating: 1550,
        newRating: 1680,
    },
    {
        contestId: 1830,
        contestName: 'Codeforces Round 880 (Div. 2)',
        handle,
        rank: 710,
        ratingUpdateTimeSeconds: Math.floor(Date.now() / 1000) - 40 * 24 * 3600,
        oldRating: 1680,
        newRating: 1630,
    },
    {
        contestId: 1840,
        contestName: 'Codeforces Round 890 (Div. 2)',
        handle,
        rank: 310,
        ratingUpdateTimeSeconds: Math.floor(Date.now() / 1000) - 20 * 24 * 3600,
        oldRating: 1630,
        newRating: 1650,
    },
];

export const generateFallbackSubmissions = (handle: string): Submission[] => [
    {
        id: 200001,
        contestId: 1840,
        creationTimeSeconds: Math.floor(Date.now() / 1000) - 2 * 3600,
        relativeTimeSeconds: 5000,
        problem: {
            contestId: 1840,
            index: 'A',
            name: 'Sasha and Array Coloring',
            type: 'PROGRAMMING',
            rating: 800,
            tags: ['greedy', 'sortings'],
        },
        author: {
            contestId: 1840,
            members: [{ handle }],
            participantType: 'PRACTICE',
            ghost: false,
        },
        programmingLanguage: 'GNU C++20',
        verdict: 'OK',
        testset: 'TESTS',
        passedTestCount: 35,
        timeConsumedMillis: 45,
        memoryConsumedBytes: 1024 * 1024,
    },
    {
        id: 200002,
        contestId: 1840,
        creationTimeSeconds: Math.floor(Date.now() / 1000) - 3 * 3600,
        relativeTimeSeconds: 6500,
        problem: {
            contestId: 1840,
            index: 'B',
            name: 'Binary Cafe',
            type: 'PROGRAMMING',
            rating: 1100,
            tags: ['bitmasks', 'math'],
        },
        author: {
            contestId: 1840,
            members: [{ handle }],
            participantType: 'PRACTICE',
            ghost: false,
        },
        programmingLanguage: 'GNU C++20',
        verdict: 'OK',
        testset: 'TESTS',
        passedTestCount: 42,
        timeConsumedMillis: 60,
        memoryConsumedBytes: 1512 * 1024,
    },
    {
        id: 200003,
        contestId: 1840,
        creationTimeSeconds: Math.floor(Date.now() / 1000) - 4 * 3600,
        relativeTimeSeconds: 8000,
        problem: {
            contestId: 1840,
            index: 'C',
            name: 'Ski Resort',
            type: 'PROGRAMMING',
            rating: 1200,
            tags: ['combinatorics', 'greedy', 'math', 'two pointers'],
        },
        author: {
            contestId: 1840,
            members: [{ handle }],
            participantType: 'PRACTICE',
            ghost: false,
        },
        programmingLanguage: 'GNU C++20',
        verdict: 'OK',
        testset: 'TESTS',
        passedTestCount: 51,
        timeConsumedMillis: 110,
        memoryConsumedBytes: 2048 * 1024,
    },
    {
        id: 200004,
        contestId: 1840,
        creationTimeSeconds: Math.floor(Date.now() / 1000) - 24 * 3600,
        relativeTimeSeconds: 12000,
        problem: {
            contestId: 1840,
            index: 'D',
            name: 'Wooden Toy Festival',
            type: 'PROGRAMMING',
            rating: 1400,
            tags: ['binary search', 'greedy', 'sortings'],
        },
        author: {
            contestId: 1840,
            members: [{ handle }],
            participantType: 'PRACTICE',
            ghost: false,
        },
        programmingLanguage: 'GNU C++20',
        verdict: 'WRONG_ANSWER',
        testset: 'TESTS',
        passedTestCount: 12,
        timeConsumedMillis: 30,
        memoryConsumedBytes: 512 * 1024,
    },
];
